# Generated by Django 5.2.13 on 2026-05-13 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.TextField()),
                ('one_star', models.TextField(blank=True)),
                ('two_star', models.TextField(blank=True)),
                ('three_star', models.TextField(blank=True)),
                ('four_star', models.TextField(blank=True)),
                ('five_star', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('governorate', models.CharField(blank=True, max_length=120)),
                ('wilayat', models.CharField(blank=True, max_length=120)),
                ('license_no', models.CharField(blank=True, max_length=100)),
                ('rooms_count', models.PositiveIntegerField(default=0)),
                ('target_stars', models.PositiveSmallIntegerField(choices=[(1, 'نجمة واحدة'), (2, 'نجمتان'), (3, 'ثلاث نجوم'), (4, 'أربع نجوم'), (5, 'خمس نجوم')], default=3)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('FINAL', 'معتمد')], default='DRAFT', max_length=20)),
                ('general_notes', models.TextField(blank=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recommendation', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='evaluations.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('OK', 'مستوفي'), ('NO', 'غير مستوفي'), ('NA', 'لا ينطبق')], default='OK', max_length=2)),
                ('note', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.criterion')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='evaluations.evaluation')),
            ],
            options={
                'unique_together': {('evaluation', 'criterion')},
            },
        ),
        migrations.CreateModel(
            name='ResponseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evaluation_images/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='evaluations.response')),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='evaluations.section')),
            ],
        ),
        migrations.AddField(
            model_name='criterion',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='evaluations.subsection'),
        ),
    ]
